### ISSUE TITLE
Partial on every page doesn't work

### ISSUE THREAD

**Issue by OussamaRomdhane** [nullfirm/hjs#14]
Hello, 
Thank you for the beautiful module. 
I have one complain though, partials seem to work fine when used in render but doesn't work for "every page" 

`app.set('partials', {footer: 'footer'});`

**Comment by aesinv** [comment]
This is the same issue as #2. There is support for this in the current version hosted here on github but the author hasn't published the new version to npm. I was only able to get it to work by adding this repo as a submodule in my `node_modules` folder. I'm sure there's a more elegant submodule solution but this is what worked for me last night at 1am:

```
git submodule add -f git@github.com:nullfirm/hjs.git ./node_modules/hjs
```

Since this doesn't seem to be getting updated its probably time to switch to another view engine.

**Comment by linslin** [comment]
Due to no support on this library for months and a last release years a ago we decided to fork this lib to https://github.com/linslin/hjs and released a new version on NPM with all the latest fixes. The "bus factor" on this lib is to high. With our fork we try to get this lib back into life.

**Comment by OussamaRomdhane** [comment]
Thank you guys for the responses, I'm not sure we can change to that new module soon (not a priority) but thanks a lot and I would probably use it in upcoming projects.
Cheers!
